language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsm4labs
  api_key:
    secure: PJ2+T0P2pyGBnn+8lyUlRqaR5Wpb5JT6gHwD9tPUivDJL5Ji3INo4rvHUydEaPMFR86C7pXRb45ojXQG1eZXToESJVZRdRVQqirqR4rVZL5hkM/aygtBNU02SD4EFRKsLTj4J+L/z997WndCsa+6WWscezIZimK0NPbbB9MMuxqJ9P22kP1Dq0z15NBH1reK15yTheRb2ciZ/ca+DA6ITcmkJQZ8YGcYYYLI44I28dFQAFCtYwY9llwGpdr4HZ+ClCe5Yd8vsSJzHDxOmbGCvisOHeY5DhGiu7j+qE/s1f79hWeL3MJiUa3UB+M9UUOT/YeUQFpTtqiIzUG1pXbq8aA292t0E4s2VZHCHDzvGdreC3/wtLi48iP5gGxlx8/hjbODs7pV/p6Sd+zdPJtOPXFBesS2dLwO8XpC7gQovK1iAbno7F6ooiUKplWo2bxtVBZwrHuA2Z6tQHWYzZxdpJwcgITXW5rQM3uPchSZ+Zlz29UZQ1hfdCO07Q0J60hLOWWVF59aoLFlv+5Pm0qScPyVVFqTJl6ldo5wt5RO5cmJYGFd3//oyRYqp3sxfSxmNdCDcPLnOLNq2gwRJxkuBCr25sYDY3a5vXeeY176h42hcB+ZzN55pEMGA8x/x4gJlAqC1U3/NaQ/FFOdlOsnkwL1Tsyfj1yNnPYs6kLI7UI=
